/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Vaccine;
import Model.*;
import javax.swing.JOptionPane;
/**
 *
 * @author xyh10
 */
public class AddVaccinePanel extends javax.swing.JPanel {

    /**
     * Creates new form AddVaccinePanel
     */
    Business business;
    Applicant selectedApplicant;
    
    public AddVaccinePanel() {
        initComponents();
    }
    
        
    public AddVaccinePanel(Business business) {
        initComponents();
        this.business = business;
        display();
    }
    
    public void display(){
        
        for(Applicant a:business.getApplicantsDirectory().getApplicantCatalog()){
            combox.addItem(a);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        combox = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldVaccinationName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fieldCourseCompleted = new javax.swing.JCheckBox();
        addBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setForeground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        combox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- choose an applicant --" }));
        combox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxActionPerformed(evt);
            }
        });
        add(combox, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 174, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Choose the Applicant");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Vaccination Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));
        add(fieldVaccinationName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 110, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Course Completed");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        fieldCourseCompleted.setForeground(new java.awt.Color(0, 0, 0));
        fieldCourseCompleted.setText("yes");
        add(fieldCourseCompleted, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 390, -1, -1));

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Add Vaccination Details");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Vaccination Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        if(selectedApplicant == null){
            JOptionPane.showMessageDialog(null, "Please select a application!");
            return ;
        }
        
        if(fieldVaccinationName.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter vaccination name!");
            return ;
        }
        
        selectedApplicant.getPet().createVaccination(fieldVaccinationName.getText(), fieldCourseCompleted.isSelected());
        JOptionPane.showMessageDialog(null, "Added successfully!");
    }//GEN-LAST:event_addBtnActionPerformed

    private void comboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxActionPerformed
        // TODO add your handling code here:
        if(combox.getSelectedIndex() == 0){
            selectedApplicant = null;
        }else{
            selectedApplicant = (Applicant) combox.getSelectedItem();
        }
    }//GEN-LAST:event_comboxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JComboBox combox;
    private javax.swing.JCheckBox fieldCourseCompleted;
    private javax.swing.JTextField fieldVaccinationName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
