/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Vaccine;
import Model.*;
import javax.swing.JOptionPane;

/**
 *
 * @author xyh10
 */
public class DeleteVaccinePanel extends javax.swing.JPanel {

    /**
     * Creates new form DeleteVaccinePanel
     */
    Business business;
    Applicant selectedApplicant;
    Vaccination selectedVaccination;
    public DeleteVaccinePanel() {
        initComponents();
    }
    
        
    public DeleteVaccinePanel(Business business) {
        initComponents();
        this.business = business;
        displayApplicant();
    }
        
    public void displayApplicant(){
//        for(int i=comboxApplicant.getItemCount() -1; i>0; i--){
//            comboxApplicant.removeItemAt(i);
//        }
        
        for(Applicant a:business.getApplicantsDirectory().getApplicantCatalog()){
            comboxApplicant.addItem(a);
        }
    }
    
    public void displayVaccination(){
        for(int i=comboxVaccination.getItemCount() -1; i>0; i--){
            comboxVaccination.removeItemAt(i);
        }
        
        for(Vaccination v:selectedApplicant.getPet().getVaccinationHistory()){
            comboxVaccination.addItem(v);
        }
    }
    
    public void clean(){
        fieldVaccinationName.setText("");
        fieldCourseCompleted.setSelected(false);
                

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboxApplicant = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        comboxVaccination = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fieldCourseCompleted = new javax.swing.JCheckBox();
        fieldVaccinationName = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 255));
        setMinimumSize(new java.awt.Dimension(800, 500));

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Delete Vaccination Details");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Choose Applicant");

        comboxApplicant.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- choose an applicant --" }));
        comboxApplicant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxApplicantActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Choose Vaccination Plan");

        comboxVaccination.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- choose a vaccination plan --" }));
        comboxVaccination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxVaccinationActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Vaccination Details");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Vaccination Name");

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Course Completed");

        fieldCourseCompleted.setForeground(new java.awt.Color(0, 0, 0));
        fieldCourseCompleted.setText("yes");
        fieldCourseCompleted.setEnabled(false);

        fieldVaccinationName.setEditable(false);

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(627, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(101, 101, 101))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel12))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(8, 8, 8)
                            .addComponent(comboxApplicant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(70, 70, 70)
                            .addComponent(jLabel2)
                            .addGap(8, 8, 8)
                            .addComponent(comboxVaccination, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel11))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel4)
                            .addGap(45, 45, 45)
                            .addComponent(fieldVaccinationName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(jLabel5)
                            .addGap(41, 41, 41)
                            .addComponent(fieldCourseCompleted)))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(402, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(75, 75, 75))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addGap(26, 26, 26)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3)
                        .addComponent(comboxApplicant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(comboxVaccination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(87, 87, 87)
                    .addComponent(jLabel11)
                    .addGap(63, 63, 63)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addComponent(fieldVaccinationName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(67, 67, 67)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel5)
                        .addComponent(fieldCourseCompleted))
                    .addGap(0, 75, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void comboxApplicantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxApplicantActionPerformed
        // TODO add your handling code here:
        if(comboxApplicant.getSelectedIndex() == 0){
            selectedApplicant = null;
            selectedVaccination = null;
            for(int i=comboxVaccination.getItemCount() -1; i> 0; i--){
                comboxVaccination.removeItemAt(i);
            }
            clean();

        }else{
            selectedApplicant = (Applicant) comboxApplicant.getSelectedItem();
            displayVaccination();
        }
    }//GEN-LAST:event_comboxApplicantActionPerformed

    private void comboxVaccinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxVaccinationActionPerformed
        // TODO add your handling code here:
        if(comboxVaccination.getSelectedIndex() == 0){
            selectedVaccination = null;
            clean();
        }else{
            selectedVaccination = (Vaccination) comboxVaccination.getSelectedItem();

            fieldVaccinationName.setText(selectedVaccination.getName());
            fieldCourseCompleted.setSelected(selectedVaccination.isCourseCompleted());
        }
    }//GEN-LAST:event_comboxVaccinationActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(selectedVaccination == null){
            JOptionPane.showMessageDialog(null, "Select a vaccination plan!");
            return ;
        }
        
        selectedApplicant.getPet().getVaccinationHistory().remove(selectedVaccination);
        selectedApplicant = null;
        selectedVaccination = null;

        clean();
                
        for(int i=comboxVaccination.getItemCount() -1; i>0; i--){
            comboxVaccination.removeItemAt(i);
        }

        JOptionPane.showMessageDialog(null, "Deleted!");

    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboxApplicant;
    private javax.swing.JComboBox comboxVaccination;
    private javax.swing.JCheckBox fieldCourseCompleted;
    private javax.swing.JTextField fieldVaccinationName;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
