/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Vaccine;
import Model.*;
import javax.swing.JOptionPane;
/**
 *
 * @author xyh10
 */
public class UpdateVaccinePanel extends javax.swing.JPanel {

    /**
     * Creates new form UpdateVaccinePanel
     */
    Business business;
    Applicant selectedApplicant;
    Vaccination selectedVaccination;
    
    public UpdateVaccinePanel() {
        initComponents();
    }
    
        
    public UpdateVaccinePanel(Business business) {
        initComponents();
        this.business = business;
        displayApplicant();
    }
    
    public void displayApplicant(){
//        for(int i=comboxApplicant.getItemCount() -1; i>0; i--){
//            comboxApplicant.removeItemAt(i);
//        }
        
        for(Applicant a:business.getApplicantsDirectory().getApplicantCatalog()){
            comboxApplicant.addItem(a);
        }
    }
    
    public void displayVaccination(){
        for(int i=comboxVaccination.getItemCount() -1; i>0; i--){
            comboxVaccination.removeItemAt(i);
        }
        
        for(Vaccination v:selectedApplicant.getPet().getVaccinationHistory()){
            comboxVaccination.addItem(v);
        }
    }
    
    public void clean(){
        fieldVaccinationName.setText("");
        fieldCourseCompleted.setSelected(false);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        comboxVaccination = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        fieldVaccinationName = new javax.swing.JTextField();
        fieldCourseCompleted = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        comboxApplicant = new javax.swing.JComboBox();

        setBackground(new java.awt.Color(255, 204, 204));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Choose Vaccination Plan");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, 20));

        comboxVaccination.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- choose a vaccination plan --" }));
        comboxVaccination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxVaccinationActionPerformed(evt);
            }
        });
        add(comboxVaccination, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 100, 210, -1));

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Update Vaccination Details");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Vaccination Name");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));
        add(fieldVaccinationName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 110, -1));

        fieldCourseCompleted.setForeground(new java.awt.Color(0, 0, 0));
        fieldCourseCompleted.setText("yes");
        add(fieldCourseCompleted, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Course Completed");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, -1, -1));

        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 380, -1, -1));

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Vaccination Details");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Choose Applicant");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        comboxApplicant.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- choose an applicant --" }));
        comboxApplicant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboxApplicantActionPerformed(evt);
            }
        });
        add(comboxApplicant, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 180, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void comboxApplicantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxApplicantActionPerformed
        // TODO add your handling code here:
        if(comboxApplicant.getSelectedIndex() == 0){
            selectedApplicant = null;
            selectedVaccination = null;
            for(int i=comboxVaccination.getItemCount() -1; i> 0; i--){
                comboxVaccination.removeItemAt(i);
            }
            clean();
            
        }else{
            selectedApplicant = (Applicant) comboxApplicant.getSelectedItem();
            displayVaccination();
        }
    }//GEN-LAST:event_comboxApplicantActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if(selectedVaccination == null){
            JOptionPane.showMessageDialog(null, "Select a vaccination plan!");
            return ;
        }
        
        if(fieldVaccinationName.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter the vaccination name!");
            return ;
        }
        
        selectedVaccination.setName(fieldVaccinationName.getText());
        selectedVaccination.setCourseCompleted(fieldCourseCompleted.isSelected());
        
        
        
        clean();
                
        for(int i=comboxVaccination.getItemCount() -1; i>0; i--){
            comboxVaccination.removeItemAt(i);
        }
                
//        for(int i=comboxApplicant.getItemCount() -1; i>0; i--){
//            comboxApplicant.removeItemAt(i);
//        }
        JOptionPane.showMessageDialog(null, "Updated!");
        

            
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void comboxVaccinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboxVaccinationActionPerformed
        // TODO add your handling code here:
        if(comboxVaccination.getSelectedIndex() == 0){
            selectedVaccination = null;
            clean();
        }else{
            selectedVaccination = (Vaccination) comboxVaccination.getSelectedItem();
            
            fieldVaccinationName.setText(selectedVaccination.getName());
            fieldCourseCompleted.setSelected(selectedVaccination.isCourseCompleted());
        }
    }//GEN-LAST:event_comboxVaccinationActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboxApplicant;
    private javax.swing.JComboBox comboxVaccination;
    private javax.swing.JCheckBox fieldCourseCompleted;
    private javax.swing.JTextField fieldVaccinationName;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
