/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Insurance;

import javax.swing.JOptionPane;
import Model.*;

/**
 *
 * @author xyh10
 */
public class InsuranceAddPanel extends javax.swing.JPanel {

    /**
     * Creates new form InsuranceAddPanel
     */
    Business business ;
    public InsuranceAddPanel() {
        initComponents();
    }
        
    public InsuranceAddPanel(Business business) {
        initComponents();
        this.business = business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fieldPlanName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        fieldPlanID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fieldCostMonth = new javax.swing.JTextField();
        fieldCostAnnum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 153));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(fieldPlanName, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 110, -1));

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Plan Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Plan ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, -1, -1));
        add(fieldPlanID, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 110, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Cost per Cost");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        fieldCostMonth.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldCostMonthFocusLost(evt);
            }
        });
        add(fieldCostMonth, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 110, -1));

        fieldCostAnnum.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                fieldCostAnnumFocusLost(evt);
            }
        });
        fieldCostAnnum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCostAnnumActionPerformed(evt);
            }
        });
        add(fieldCostAnnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 110, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Cost per Annum");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, -1, -1));

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Add Insurance Plan");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(fieldPlanID.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter Plan ID");
            return ;
        }
        
        if(fieldPlanName.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter Plan Name");
            return ;
        }
        
        
        if(fieldCostMonth.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter cost");
            return ;
        }
        
        Insurance ins = business.getInsuranceDirectory().createInsurance(Integer.parseInt(fieldPlanID.getText()), fieldPlanName.getText(), Double.parseDouble(fieldCostMonth.getText()));
        
        JOptionPane.showMessageDialog(null, "Insurance created!");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fieldCostMonthFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCostMonthFocusLost
        // TODO add your handling code here:
        String str = fieldCostMonth.getText();
        if(str.isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter cost");
            return; 
        }else if(!str.matches("(-?)(0|([1-9][0-9]*))(\\\\.[0-9]+)?$")){
            JOptionPane.showMessageDialog(null, "Invalid value!");
            return;
        }else{
            double costM = Double.parseDouble(str);
            fieldCostAnnum.setText("" + costM*12);
        }
    }//GEN-LAST:event_fieldCostMonthFocusLost

    private void fieldCostAnnumFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_fieldCostAnnumFocusLost
        // TODO add your handling code here:
        String str = fieldCostAnnum.getText();
        if(str.isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter cost");
            return;
            
        }else if(!str.matches("(-?)(0|([1-9][0-9]*))(\\\\.[0-9]+)?$")){
            JOptionPane.showMessageDialog(null, "Invalid value!");
            return;
        }else{
            double costA = Double.parseDouble(str);
            fieldCostMonth.setText("" + costA/12);
        }
    }//GEN-LAST:event_fieldCostAnnumFocusLost

    private void fieldCostAnnumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCostAnnumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCostAnnumActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldCostAnnum;
    private javax.swing.JTextField fieldCostMonth;
    private javax.swing.JTextField fieldPlanID;
    private javax.swing.JTextField fieldPlanName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
