/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import Model.*;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author xyh10
 */
public class CreatePane extends javax.swing.JPanel {
    
    private PersonCatelog pc;
    private Person thePerson;
    private ImageIcon imageIcon;
    /**
     * Creates new form CreatePane
     */
    public CreatePane() {
        initComponents();
        pc = new PersonCatelog();
    }
    
    public CreatePane(PersonCatelog pc){
        initComponents();
        this.pc = pc;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fieldUserName = new javax.swing.JTextField();
        fieldFirstName = new javax.swing.JTextField();
        fieldLastName = new javax.swing.JTextField();
        fieldRecipeTitle = new javax.swing.JTextField();
        fieldNoOfServings = new javax.swing.JTextField();
        isGlutenFree = new javax.swing.JCheckBox();
        fieldDifficultyLevel = new javax.swing.JTextField();
        fieldNoOfIngredients = new javax.swing.JTextField();
        fieldCategoryOfFood = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        fieldEmailID = new javax.swing.JTextField();
        fieldPhone = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fieldDescription = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        imageField = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Create chef information here!");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("UserName");

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("FirstName");

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("LastName");

        jLabel5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Recipe Information");

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Recipe title");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("No. of servings");

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Is gluten free");

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Difficullty level");

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("No. of ingredients");

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Category of food");

        fieldUserName.setBackground(new java.awt.Color(255, 255, 255));

        fieldFirstName.setBackground(new java.awt.Color(255, 255, 255));

        fieldLastName.setBackground(new java.awt.Color(255, 255, 255));

        fieldRecipeTitle.setBackground(new java.awt.Color(255, 255, 255));

        fieldNoOfServings.setBackground(new java.awt.Color(255, 255, 255));

        isGlutenFree.setForeground(new java.awt.Color(0, 0, 0));
        isGlutenFree.setText("yes");

        fieldDifficultyLevel.setBackground(new java.awt.Color(255, 255, 255));

        fieldNoOfIngredients.setBackground(new java.awt.Color(255, 255, 255));

        fieldCategoryOfFood.setBackground(new java.awt.Color(255, 255, 255));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Email ID");

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Phone");

        fieldEmailID.setBackground(new java.awt.Color(255, 255, 255));

        fieldPhone.setBackground(new java.awt.Color(255, 255, 255));

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Select reicpe picture");

        fieldDescription.setBackground(new java.awt.Color(255, 255, 255));
        fieldDescription.setColumns(20);
        fieldDescription.setForeground(new java.awt.Color(0, 0, 0));
        fieldDescription.setRows(5);
        fieldDescription.setText("Enter your description here...");
        jScrollPane1.setViewportView(fieldDescription);

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Description");

        imageField.setBackground(new java.awt.Color(204, 204, 204));
        imageField.setMaximumSize(new java.awt.Dimension(200, 150));
        imageField.setMinimumSize(new java.awt.Dimension(200, 150));
        imageField.setOpaque(true);

        jButton1.setBackground(new java.awt.Color(0, 255, 51));
        jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Save");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 102, 102));
        jButton2.setText("browse");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(51, 255, 51));
        jButton3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Add recipe");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(235, 235, 235)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fieldEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(fieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton2))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(fieldNoOfServings, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(fieldRecipeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel4))
                                            .addGap(60, 60, 60)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(fieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(fieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addComponent(jLabel1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9))
                                        .addGap(40, 40, 40)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(fieldDifficultyLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(isGlutenFree)))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(fieldCategoryOfFood, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addGap(18, 18, 18)
                                            .addComponent(fieldNoOfIngredients, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(121, 121, 121)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15)
                                            .addComponent(imageField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton1)))))))
                .addGap(141, 141, 141))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(fieldEmailID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fieldLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(fieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel5)
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(fieldRecipeTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(fieldNoOfServings, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(isGlutenFree))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(fieldDifficultyLevel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(fieldNoOfIngredients, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(fieldCategoryOfFood, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jButton2))
                        .addGap(18, 18, 18)
                        .addComponent(imageField, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        /* 
        * In this method, we:
        * 1. validate all fields input
        * 2. get a user according to username or create one if not exist
        * 3. If the person already exists, check wether names are correct; if this person is newly created, then skip this part
        * 4. Create person object, and set infor
        */ 
        
        // 1. validate all fields input
        if(!validateUserName()) return;
        String username = fieldUserName.getText();
        
        if(!validateFirstName()) return;
        String firstname = fieldFirstName.getText();
        
        if(!validateLastName()) return ;
        String lastname = fieldLastName.getText();
        
        if(!validateEmailID()) return ;
        String emailID = fieldEmailID.getText();
        
        if(!validatePhone()) return;
        String phone = fieldPhone.getText();
        
        // 2. get the person acording to the username Or create a new one with this username
        Person person = pc.getOrCreate(username);
        
        // 3. check wether names are correct; if this person is newly created, then skip this part
        if(validateName(person)){
            person.setFirstName(firstname);
            person.setLastName(lastname);
            person.setEmailID(emailID);
            person.setPhone(phone);
        }  

        // 4. set person object for the JPane 
        thePerson = person;
        
        JOptionPane.showMessageDialog(this, "Chef created/found successfully!");
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        /*
        * 
        * In this method, we:
        * 0. check if person have been created
        * 1. validate all fields input
        * 2. check whether the recipe already exist(according to reicpe title)
        * 3. If the person already exists,  return warnings
        * 4. If not, create new recipe and save
        */
        
        
        // 0.
        if(thePerson == null){
            JOptionPane.showMessageDialog(null, "Please save chef information first!");
            return ;
        }
        
        // 1. validate all fields input
        if(!validateRecipeTitle()) return;
        String recipetitle = fieldRecipeTitle.getText();
        
        if(!validateNoOfServing()) return;
        long noOfservings = Long.parseLong(fieldNoOfServings.getText());
        
        boolean isGlutenFree = this.isGlutenFree.isSelected() ? true:false;
        
        if(!validateDifficultyLevel()) return;
        double difficultyLevel = Double.parseDouble(fieldDifficultyLevel.getText());
        
        if(!validateNoOfIngredient()) return;
        int noofingredient = Integer.parseInt(fieldNoOfIngredients.getText());
        
        if(!validateCategoryOfFood()) return;
        String category = fieldCategoryOfFood.getText();
        
        if(!validateDescription()) return;
        String description = fieldDescription.getText();
        
        if(!validateImage()) return;

        //2. check whether the recipe already exist(according to reicpe title)
        Recipe recipe = thePerson.findRecipe(recipetitle);
        if(recipe != null){
            JOptionPane.showMessageDialog(null, "Recipe existed! Change recipe title!");
            return ;
        }
        
        recipe = new Recipe(thePerson);
        recipe.setTitle(recipetitle);
        recipe.setNoOfServings(noOfservings);
        recipe.setIsGlutenFree(isGlutenFree);
        recipe.setDifficultyLevel(difficultyLevel);
        recipe.setNoOfIngredient(noofingredient);
        recipe.setCategory(category);
        recipe.setDescription(description);
        recipe.setImage(imageIcon);

        JOptionPane.showMessageDialog(this, "Recipe created successfully!");
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                JFileChooser jf = new JFileChooser();
        FileNameExtensionFilter fef = new FileNameExtensionFilter("Image", "jpg","png","gif", "jpeg","webp");
        jf.addChoosableFileFilter(fef);
        
        int fileDialog = jf.showOpenDialog(null);
        
        if(fileDialog == JFileChooser.APPROVE_OPTION){
            File imageFile = jf.getSelectedFile();
            String imagePath = imageFile.getAbsolutePath();
            
            ImageIcon ii = new ImageIcon(imagePath);
            Image image = ii.getImage().getScaledInstance(200, 150,Image.SCALE_SMOOTH );
            imageIcon = new ImageIcon(image) ;
            imageField.setIcon(imageIcon);
            
            System.out.println(imagePath);
            
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    
    public boolean validateUserName(){
        String str = fieldUserName.getText();
        
        // 1. is empty
        if(str.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter your userName!");
            return false;
        }else if(!Person.validateUserName(str)){   // 2. if contains only letters, digit, _, $
            JOptionPane.showMessageDialog(this, "Please enter valid userName(consists of only letters, digit, _, $!");  
            return false;
        }
        
        return true;
    }
    
    public boolean validateFirstName(){
        String str = fieldFirstName.getText();
        
        // 1. is empty
        if(str.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter your firstName!");
            return false;
        }else if(!Person.validateFirstName(str)){   // 2. if contains unvalid character
            JOptionPane.showMessageDialog(this, "Please enter valid firstName(consists of only Enhlist letters)!");  
            return false;
        }
        
        return true;
    }
    
    public boolean validateLastName(){
        String str = fieldLastName.getText();
        
        // 1. is empty
        if(str.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter your lastName!");
            return false;
        }else if(!Person.validateLastName(str)){   // 2. if contains unvalid character
            JOptionPane.showMessageDialog(this, "Please enter valid lastName(consists of only Enhlist letters)!");  
            return false;
        }
        
        return true;
    }
    
    public boolean validateEmailID(){
        String str = fieldEmailID.getText();
        
        if(str.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter your Email ID!");
            return false;
        }else if(!Person.validateEmailID(str)){
            JOptionPane.showMessageDialog(this, "Please enter valid email adress!");  
            return false;
        }
        
        return true;
    }
    
    
    public boolean validatePhone(){
        String str = fieldPhone.getText();
        
        if(str.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter your Phone!");
            return false;
        }else if(!Person.validatePhone(str)){
            JOptionPane.showMessageDialog(this, "Please enter valid 9 digit phone number!");  
            return false;
        }
        
        return true;
    }
    
    public boolean validateRecipeTitle(){
        String str = fieldRecipeTitle.getText();
        
        if(str.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter your recipe title!");
            return false;
        }else if(!Recipe.validateRecipeTitle(str)){
            JOptionPane.showMessageDialog(this, "Please enter valid recipe title(contains only letters and digits)!");  
            return false;
        }
        
        return true;
    }
    
    public boolean validateNoOfServing(){
        String str = fieldNoOfServings.getText();
        
        if(str.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter number of servings!");
            return false;
        }else if(!Recipe.validateNoOfServings(str)){
            JOptionPane.showMessageDialog(this, "Please enter valid number!");  
            return false;
        }
        
        return true;
    }
    
    public boolean validateDifficultyLevel(){
        String str = fieldDifficultyLevel.getText();
        
        if(str.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter difficulty level!");
            return false;
        }else if(Recipe.validateDifficultyLevel(str) == 1){
            JOptionPane.showMessageDialog(this, "Please enter valid number!");  
            return false;
        }else if(Recipe.validateDifficultyLevel(str) == 2){
            JOptionPane.showMessageDialog(this, "The difficulty level should range from 1 to 5!");  
            return false;
        }
        
        return true;
    }
    
    public boolean validateNoOfIngredient(){
        String str = fieldNoOfIngredients.getText();
        
        if(str.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter number of ingredient!");
            return false;
        }else if(!Recipe.validateNoOfServings(str)){
            JOptionPane.showMessageDialog(this, "Please enter valid number!");  
            return false;
        }
        
        return true;
    }
    
    public boolean validateCategoryOfFood(){
        String str = fieldCategoryOfFood.getText();
        
        if(str.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter food category!");
            return false;
        }else if(!Recipe.validateCategoryOfFood(str)){
            JOptionPane.showMessageDialog(this, "Please enter valid category(consists only of English letters)!");  
            return false;
        }
        
        return true;
    }
    
    public boolean validateDescription(){
        // check whether is empty 
        String str = fieldDescription.getText();
        
        if(str.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter desciption!");
            return false;
        }else if(str.equals("Enter your description here...")){
            JOptionPane.showMessageDialog(this, "Please enter desciption!");
            return false;
        }
        
        return true;
    }
    
    public boolean validateName(Person p){
        //check wether names are correct; if this person is newly created, then skip this part
        if(p.getFirstName().equals("unkown") && p.getLastName().equals("unkown")){
            return true;
        }else if(!p.getFirstName().equals(fieldFirstName.getText())){
            JOptionPane.showMessageDialog(this, "First Name is incorrect! Go to update page to update information if needed!");
            return false;
        }else if(!p.getLastName().equals(fieldLastName.getText())){
            JOptionPane.showMessageDialog(this, "Last Name is incorrect! Go to update page to update information if needed!");
            return false;
        }
        
        return true;
    }
    
    public boolean validateImage(){
        if(imageIcon == null){
            JOptionPane.showMessageDialog(this, "please upload an image!");
            return false;
        }
        
        return true;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldCategoryOfFood;
    private javax.swing.JTextArea fieldDescription;
    private javax.swing.JTextField fieldDifficultyLevel;
    private javax.swing.JTextField fieldEmailID;
    private javax.swing.JTextField fieldFirstName;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldNoOfIngredients;
    private javax.swing.JTextField fieldNoOfServings;
    private javax.swing.JTextField fieldPhone;
    private javax.swing.JTextField fieldRecipeTitle;
    private javax.swing.JTextField fieldUserName;
    private javax.swing.JLabel imageField;
    private javax.swing.JCheckBox isGlutenFree;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
