/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Recipe;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author xyh10
 */
public class ReadDetailedInfo extends javax.swing.JPanel {
    private Recipe recipe;
    private Main main;
    
    /**
     * Creates new form ReadDetailedInfo
     */
    public ReadDetailedInfo() {
        initComponents();
    }
    
    public ReadDetailedInfo(Recipe recipe, Main main){
        initComponents();
        this.recipe = recipe;
        this.main = main;
        display();
    }
    
    public void display(){
        fieldUserName.setText(recipe.getPerson().getUserName());
        fieldFirstName.setText(recipe.getPerson().getFirstName());
        fieldLastName.setText(recipe.getPerson().getLastName());
        fieldEmailID.setText(recipe.getPerson().getEmailID());
        fieldPhone.setText(recipe.getPerson().getPhone());
        fieldRecipeTitle.setText(recipe.getTitle());
        fieldNoOfServings.setText("" + recipe.getNoOfServings());
        isGlutenFree.setSelected(recipe.isIsGlutenFree());
        fieldDifficultyLevel.setText("" + recipe.getDifficultyLevel());
        fieldCategoryOfFood.setText(recipe.getCategory());
        
        
        Image image = recipe.getImage().getImage().getScaledInstance(200, 150,Image.SCALE_SMOOTH );
        imageField.setIcon(new ImageIcon(image));
        
        fieldDescription.setText(recipe.getDescription());
        
        
        
        fieldUserName.setEditable(false);
        fieldFirstName.setEditable(false);
        fieldLastName.setEditable(false);
        fieldEmailID.setEditable(false);
        fieldPhone.setEditable(false);
        fieldRecipeTitle.setEditable(false);
        fieldNoOfServings.setEditable(false);
        fieldDifficultyLevel.setEditable(false);
        fieldCategoryOfFood.setEditable(false);
        
        fieldDescription.setEditable(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Picture = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fieldUserName = new javax.swing.JTextField();
        fieldFirstName = new javax.swing.JTextField();
        fieldLastName = new javax.swing.JTextField();
        fieldRecipeTitle = new javax.swing.JTextField();
        fieldNoOfServings = new javax.swing.JTextField();
        fieldDifficultyLevel = new javax.swing.JTextField();
        fieldNoOfIngredients = new javax.swing.JTextField();
        fieldCategoryOfFood = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        fieldEmailID = new javax.swing.JTextField();
        fieldPhone = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        imageField = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fieldDescription = new javax.swing.JTextArea();
        isGlutenFree = new javax.swing.JCheckBox();

        setPreferredSize(new java.awt.Dimension(800, 600));

        Picture.setBackground(new java.awt.Color(153, 255, 153));
        Picture.setForeground(new java.awt.Color(0, 0, 0));
        Picture.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        Picture.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(703, 532, -1, -1));

        jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Detail Information");
        Picture.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 60, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("UserName");
        Picture.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 107, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("FirstName");
        Picture.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 152, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("LastName");
        Picture.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 194, -1, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Recipe Information");
        Picture.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 225, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Recipe title");
        Picture.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 265, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("No. of Servings");
        Picture.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 308, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Is gluten free");
        Picture.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 353, -1, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Difficulty level");
        Picture.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 409, -1, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("No. of ingredients");
        Picture.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 458, -1, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Category of food");
        Picture.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 524, -1, -1));

        fieldUserName.setBackground(new java.awt.Color(255, 255, 255));
        fieldUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldUserNameActionPerformed(evt);
            }
        });
        Picture.add(fieldUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 104, 110, -1));

        fieldFirstName.setBackground(new java.awt.Color(255, 255, 255));
        Picture.add(fieldFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 149, 110, -1));

        fieldLastName.setBackground(new java.awt.Color(255, 255, 255));
        Picture.add(fieldLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 191, 110, -1));

        fieldRecipeTitle.setBackground(new java.awt.Color(255, 255, 255));
        Picture.add(fieldRecipeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 262, 110, -1));

        fieldNoOfServings.setBackground(new java.awt.Color(255, 255, 255));
        Picture.add(fieldNoOfServings, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 305, 110, -1));

        fieldDifficultyLevel.setBackground(new java.awt.Color(255, 255, 255));
        Picture.add(fieldDifficultyLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 406, 110, -1));

        fieldNoOfIngredients.setBackground(new java.awt.Color(255, 255, 255));
        Picture.add(fieldNoOfIngredients, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 455, 110, -1));

        fieldCategoryOfFood.setBackground(new java.awt.Color(255, 255, 255));
        Picture.add(fieldCategoryOfFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 521, 110, -1));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Email ID");
        Picture.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 107, -1, -1));

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Phone");
        Picture.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 152, -1, -1));

        fieldEmailID.setBackground(new java.awt.Color(255, 255, 255));
        Picture.add(fieldEmailID, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 104, 149, -1));

        fieldPhone.setBackground(new java.awt.Color(255, 255, 255));
        Picture.add(fieldPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(457, 149, 149, -1));

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Picture");
        Picture.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 256, -1, -1));

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Description");
        Picture.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(403, 441, -1, -1));

        imageField.setBackground(new java.awt.Color(204, 204, 204));
        imageField.setOpaque(true);
        Picture.add(imageField, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 279, 200, 150));

        fieldDescription.setBackground(new java.awt.Color(255, 255, 255));
        fieldDescription.setColumns(20);
        fieldDescription.setRows(5);
        jScrollPane1.setViewportView(fieldDescription);

        Picture.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(433, 464, -1, -1));

        isGlutenFree.setForeground(new java.awt.Color(0, 0, 0));
        isGlutenFree.setText("yes");
        Picture.add(isGlutenFree, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 351, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Picture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Picture, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        main.goBackReadPaneMain();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void fieldUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldUserNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Picture;
    private javax.swing.JTextField fieldCategoryOfFood;
    private javax.swing.JTextArea fieldDescription;
    private javax.swing.JTextField fieldDifficultyLevel;
    private javax.swing.JTextField fieldEmailID;
    private javax.swing.JTextField fieldFirstName;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldNoOfIngredients;
    private javax.swing.JTextField fieldNoOfServings;
    private javax.swing.JTextField fieldPhone;
    private javax.swing.JTextField fieldRecipeTitle;
    private javax.swing.JTextField fieldUserName;
    private javax.swing.JLabel imageField;
    private javax.swing.JCheckBox isGlutenFree;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
