/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;
import Model.*;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author xyh10
 */
public class UpdatePane extends javax.swing.JPanel {
    
    private PersonCatelog pc;
    private Person thePerson;
    private ImageIcon imageIcon;
    private Recipe theRecipe;
    /**
     * Creates new form UpdatePane
     */
    public UpdatePane() {
        initComponents();
        pc = new PersonCatelog();
        fieldRecipeTitle.setEditable(false);
    }
    
    public UpdatePane(PersonCatelog pc){
        initComponents();
        this.pc = pc;
        fieldRecipeTitle.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fieldUserName = new javax.swing.JTextField();
        fieldFirstName = new javax.swing.JTextField();
        fieldLastName = new javax.swing.JTextField();
        fieldRecipeTitle = new javax.swing.JTextField();
        fieldNoOfServings = new javax.swing.JTextField();
        isGlutenFree = new javax.swing.JCheckBox();
        fieldDifficultyLevel = new javax.swing.JTextField();
        fieldNoOfIngredients = new javax.swing.JTextField();
        fieldCategoryOfFood = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        fieldEmailID = new javax.swing.JTextField();
        fieldPhone = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        fieldDescription = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        imageField = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        comboBox = new javax.swing.JComboBox<>();

        setMinimumSize(new java.awt.Dimension(800, 600));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Search chef and recipe here:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 43, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("UserName");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(365, 49, -1, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("FirstName");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 103, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("LastName");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 154, -1, -1));

        jLabel5.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Select recipe");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 188, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Recipe title");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 276, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("No. of servings");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 328, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Is gluten free");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 374, -1, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Difficullty level");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 427, -1, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("No. of ingredients");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 482, -1, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Category of food");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 530, -1, -1));

        fieldUserName.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(fieldUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 46, 110, -1));

        fieldFirstName.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(fieldFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 100, 110, -1));

        fieldLastName.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(fieldLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(175, 151, 110, -1));

        fieldRecipeTitle.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(fieldRecipeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 273, 110, -1));

        fieldNoOfServings.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(fieldNoOfServings, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 325, 110, -1));

        isGlutenFree.setForeground(new java.awt.Color(0, 0, 0));
        isGlutenFree.setText("yes");
        jPanel1.add(isGlutenFree, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 372, -1, -1));

        fieldDifficultyLevel.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(fieldDifficultyLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 424, 110, -1));

        fieldNoOfIngredients.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(fieldNoOfIngredients, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 479, 110, -1));

        fieldCategoryOfFood.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(fieldCategoryOfFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 527, 110, -1));

        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Email ID");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 103, -1, -1));

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Phone");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 154, -1, -1));

        fieldEmailID.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(fieldEmailID, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 100, 110, -1));

        fieldPhone.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(fieldPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(588, 151, 110, -1));

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Select reicpe picture");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 232, -1, -1));

        fieldDescription.setBackground(new java.awt.Color(255, 255, 255));
        fieldDescription.setColumns(20);
        fieldDescription.setRows(5);
        jScrollPane1.setViewportView(fieldDescription);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 459, 263, -1));

        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Description");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 430, -1, -1));

        imageField.setMaximumSize(new java.awt.Dimension(200, 150));
        imageField.setMinimumSize(new java.awt.Dimension(200, 150));
        imageField.setOpaque(true);
        jPanel1.add(imageField, new org.netbeans.lib.awtextra.AbsoluteConstraints(435, 270, 263, 151));

        jButton1.setBackground(new java.awt.Color(0, 0, 204));
        jButton1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 44, -1, -1));

        jButton2.setText("browse");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(625, 229, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 255));
        jButton3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 556, -1, -1));

        comboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- Choose the Recipe --" }));
        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });
        jPanel1.add(comboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 220, 232, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 840, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!validateUserName()) return;
        String username = fieldUserName.getText();
        
        Person person = pc.getPerson(username);
        if(person == null){
            JOptionPane.showMessageDialog(null, "Chef not found!");
            return ;
        }
        JOptionPane.showMessageDialog(null, "Chef is found, enter the information you want to change!");
        thePerson = person;
        display();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
        // TODO add your handling code here:
        String selectedRecipeName = comboBox.getSelectedItem().toString();
        
        // if choose nothing
        if(comboBox.getSelectedIndex() == 0){
            theRecipe = null;
            fieldRecipeTitle.setText("");
            fieldNoOfServings.setText( "");
            isGlutenFree.setSelected(false);
            fieldDifficultyLevel.setText("");
            fieldNoOfIngredients.setText("");
            fieldCategoryOfFood.setText("");
            fieldDescription.setText("");
            //imageIcon = recipe.getImage();
            imageField.setIcon(null);
            //imageField.setText("");
            
            
            
            
            return ;
        }
        Recipe recipe = thePerson.findRecipe(selectedRecipeName);
        
        
        fieldRecipeTitle.setText(recipe.getTitle());
        fieldNoOfServings.setText(recipe.getNoOfServings() + "");
        isGlutenFree.setSelected(recipe.isIsGlutenFree());
        fieldDifficultyLevel.setText(recipe.getDifficultyLevel() + "");
        fieldNoOfIngredients.setText(recipe.getNoOfIngredient() + "");
        fieldCategoryOfFood.setText(recipe.getCategory());
        fieldDescription.setText(recipe.getDescription());
        imageIcon = recipe.getImage();
        imageField.setIcon(imageIcon);
        
        theRecipe = recipe;
        
        
        
    }//GEN-LAST:event_comboBoxActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         /*
        * In this method, we:
        * 1. validate all fields input
        * 2. update info
        */
  
        // 1. validate all fields input
        if(!validateRecipeTitle()) return;
        String recipetitle = fieldRecipeTitle.getText();
        
        if(!validateNoOfServing()) return;
        long noOfservings = Long.parseLong(fieldNoOfServings.getText());
        
        boolean isGlutenFree = this.isGlutenFree.isSelected() ? true:false;
        
        if(!validateDifficultyLevel()) return;
        double difficultyLevel = Double.parseDouble(fieldDifficultyLevel.getText());
        
        if(!validateNoOfIngredient()) return;
        int noofingredient = Integer.parseInt(fieldNoOfIngredients.getText());
        
        if(!validateCategoryOfFood()) return;
        String category = fieldCategoryOfFood.getText();
        
        if(!validateDescription()) return;
        String description = fieldDescription.getText();
        
        if(!validateImage()) return;


        

        theRecipe.setNoOfServings(noOfservings);
        theRecipe.setIsGlutenFree(isGlutenFree);
        theRecipe.setDifficultyLevel(difficultyLevel);
        theRecipe.setNoOfIngredient(noofingredient);
        theRecipe.setCategory(category);
        theRecipe.setDescription(description);
        theRecipe.setImage(imageIcon);
        
//        ImageIcon ii = new ImageIcon(imagePath);
//            Image image = ii.getImage().getScaledInstance(imageField.getWidth(), imageField.getHeight(),Image.SCALE_SMOOTH );
//            imageIcon = new ImageIcon(image) ;
//            imageField.setIcon(imageIcon);

        JOptionPane.showMessageDialog(this, "Recipe updated successfully!");
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFileChooser jf = new JFileChooser();
        FileNameExtensionFilter fef = new FileNameExtensionFilter("Image", "jpg","png","gif", "jpeg","webp");
        jf.addChoosableFileFilter(fef);
        
        int fileDialog = jf.showOpenDialog(null);
        
        if(fileDialog == JFileChooser.APPROVE_OPTION){
            File imageFile = jf.getSelectedFile();
            if(imageFile == null){
                JOptionPane.showMessageDialog(null, "please choose an image");
                return ;
            }
            String imagePath = imageFile.getAbsolutePath();
            
            ImageIcon ii = new ImageIcon(imagePath);
            Image image = ii.getImage().getScaledInstance(200, 150,Image.SCALE_SMOOTH );
            imageIcon = new ImageIcon(image) ;
            imageField.setIcon(imageIcon);
            
            System.out.println(imagePath);
            
            
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed
    
    public void display(){
        fieldFirstName.setText(thePerson.getFirstName());
        fieldLastName.setText(thePerson.getLastName());
        fieldEmailID.setText(thePerson.getEmailID());
        fieldPhone.setText(thePerson.getPhone());
        
        for(Recipe recipe:thePerson.getRecipes()){
            comboBox.addItem(recipe.getTitle());
        }
    }
    
    
    public boolean validateUserName(){
        String str = fieldUserName.getText();
        
        // 1. is empty
        if(str.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter your userName!");
            return false;
        }else if(!Person.validateUserName(str)){   // 2. if contains only letters, digit, _, $
            JOptionPane.showMessageDialog(this, "Please enter valid userName(consists of only letters, digit, _, $!");  
            return false;
        }
        
        return true;
    }
    
    public boolean validateFirstName(){
        String str = fieldFirstName.getText();
        
        // 1. is empty
        if(str.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter your firstName!");
            return false;
        }else if(!Person.validateFirstName(str)){   // 2. if contains unvalid character
            JOptionPane.showMessageDialog(this, "Please enter valid firstName(consists of only Enhlist letters)!");  
            return false;
        }
        
        return true;
    }
    
    public boolean validateLastName(){
        String str = fieldLastName.getText();
        
        // 1. is empty
        if(str.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter your lastName!");
            return false;
        }else if(!Person.validateLastName(str)){   // 2. if contains unvalid character
            JOptionPane.showMessageDialog(this, "Please enter valid lastName(consists of only Enhlist letters)!");  
            return false;
        }
        
        return true;
    }
    
    public boolean validateEmailID(){
        String str = fieldEmailID.getText();
        
        if(str.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter your Email ID!");
            return false;
        }else if(!Person.validateEmailID(str)){
            JOptionPane.showMessageDialog(this, "Please enter valid email adress!");  
            return false;
        }
        
        return true;
    }
    
    
    public boolean validatePhone(){
        String str = fieldPhone.getText();
        
        if(str.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter your Phone!");
            return false;
        }else if(!Person.validatePhone(str)){
            JOptionPane.showMessageDialog(this, "Please enter valid 10 digit phone number!");  
            return false;
        }
        
        return true;
    }
    
    public boolean validateRecipeTitle(){
        String str = fieldRecipeTitle.getText();
        
        if(str.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter your recipe title!");
            return false;
        }else if(!Recipe.validateRecipeTitle(str)){
            JOptionPane.showMessageDialog(this, "Please enter valid recipe title(contains only letters and digits)!");  
            return false;
        }
        
        return true;
    }
    
    public boolean validateNoOfServing(){
        String str = fieldNoOfServings.getText();
        
        if(str.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter number of servings!");
            return false;
        }else if(!Recipe.validateNoOfServings(str)){
            JOptionPane.showMessageDialog(this, "Please enter valid number!");  
            return false;
        }
        
        return true;
    }
    
    public boolean validateDifficultyLevel(){
        String str = fieldDifficultyLevel.getText();
        
        if(str.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter difficulty level!");
            return false;
        }else if(Recipe.validateDifficultyLevel(str) == 1){
            JOptionPane.showMessageDialog(this, "Please enter valid number!");  
            return false;
        }else if(Recipe.validateDifficultyLevel(str) == 2){
            JOptionPane.showMessageDialog(this, "The difficulty level should range from 1 to 5!");  
            return false;
        }
        
        return true;
    }
    
    public boolean validateNoOfIngredient(){
        String str = fieldNoOfIngredients.getText();
        
        if(str.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter number of ingredient!");
            return false;
        }else if(!Recipe.validateNoOfServings(str)){
            JOptionPane.showMessageDialog(this, "Please enter valid number!");  
            return false;
        }
        
        return true;
    }
    
    public boolean validateCategoryOfFood(){
        String str = fieldCategoryOfFood.getText();
        
        if(str.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter food category!");
            return false;
        }else if(!Recipe.validateCategoryOfFood(str)){
            JOptionPane.showMessageDialog(this, "Please enter valid category(consists only of English letters)!");  
            return false;
        }
        
        return true;
    }
    
    public boolean validateDescription(){
        // check whether is empty 
        String str = fieldDescription.getText();
        
        if(str.trim().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter desciption!");
            return false;
        }else if(str.equals("Enter your description here...")){
            JOptionPane.showMessageDialog(this, "Please enter desciption!");
            return false;
        }
        
        return true;
    }
    
    public boolean validateName(Person p){
        //check wether names are correct; if this person is newly created, then skip this part
        if(p.getFirstName().equals("unkown") && p.getLastName().equals("unkown")){
            return true;
        }else if(!p.getFirstName().equals(fieldFirstName.getText())){
            JOptionPane.showMessageDialog(this, "First Name is incorrect! Go to update page to update information if needed!");
            return false;
        }else if(!p.getLastName().equals(fieldLastName.getText())){
            JOptionPane.showMessageDialog(this, "Last Name is incorrect! Go to update page to update information if needed!");
            return false;
        }
        
        return true;
    }
    
    public boolean validateImage(){
        if(imageIcon == null){
            JOptionPane.showMessageDialog(this, "please upload an image!");
            return false;
        }
        
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboBox;
    private javax.swing.JTextField fieldCategoryOfFood;
    private javax.swing.JTextArea fieldDescription;
    private javax.swing.JTextField fieldDifficultyLevel;
    private javax.swing.JTextField fieldEmailID;
    private javax.swing.JTextField fieldFirstName;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldNoOfIngredients;
    private javax.swing.JTextField fieldNoOfServings;
    private javax.swing.JTextField fieldPhone;
    private javax.swing.JTextField fieldRecipeTitle;
    private javax.swing.JTextField fieldUserName;
    private javax.swing.JLabel imageField;
    private javax.swing.JCheckBox isGlutenFree;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
