/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Applicant;

import Model.*;
import javax.swing.JOptionPane;

/**
 *
 * @author xyh10
 */
public class ApplicantAddPanel extends javax.swing.JPanel {

    /**
     * Creates new form ApplicantAddPanel
     */
    Business business;
    public ApplicantAddPanel() {
        initComponents();
    }
    
    public ApplicantAddPanel(Business business){
        initComponents();
        this.business = business;
        display();
    }
        
    public void display(){
        for(Insurance ins:business.getInsuranceDirectory().getInsuranceCatalog()){
            fieldPlan.addItem(ins);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fieldFirstName = new javax.swing.JTextField();
        fieldLastName = new javax.swing.JTextField();
        fieldPetName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fieldDate = new com.toedter.calendar.JDateChooser();
        fieldPetAge = new javax.swing.JTextField();
        fieldPetType = new javax.swing.JTextField();
        fieldPetBreed = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        fieldPlan = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        fieldVaccinationName = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        fieldCourseCompleted = new javax.swing.JCheckBox();
        fieldPetGender = new javax.swing.JCheckBox();

        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Applicant Info");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        fieldFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldFirstNameActionPerformed(evt);
            }
        });
        jPanel1.add(fieldFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 110, -1));
        jPanel1.add(fieldLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 150, 110, -1));
        jPanel1.add(fieldPetName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 110, -1));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Pet's Info");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));
        jPanel1.add(fieldDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 230, -1));
        jPanel1.add(fieldPetAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 310, 110, -1));
        jPanel1.add(fieldPetType, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 110, -1));
        jPanel1.add(fieldPetBreed, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 110, -1));

        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("FirstName");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("LastName");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Date");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Pet Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Age");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, -1));

        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Gender");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, -1, -1));

        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Pet Type");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));

        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Breed");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, -1, -1));

        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Inurance Plan");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, -1, -1));

        fieldPlan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-- choose a plan --" }));
        jPanel1.add(fieldPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 370, 250, -1));

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Add Application & Pet Information");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, -1, -1));

        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Vaccination Name");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, -1, -1));
        jPanel1.add(fieldVaccinationName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 110, -1));

        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Course Completed");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, -1, -1));

        fieldCourseCompleted.setForeground(new java.awt.Color(0, 0, 0));
        fieldCourseCompleted.setText("yes");
        jPanel1.add(fieldCourseCompleted, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 420, -1, -1));

        fieldPetGender.setForeground(new java.awt.Color(0, 0, 0));
        fieldPetGender.setText("male");
        jPanel1.add(fieldPetGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldFirstNameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        // validate if null
        if(fieldFirstName.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter first name!");
            return ;
        }
        
        if(fieldLastName.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter last name!");
            return ;
        }
        
        if(fieldDate.getDate() == null){
            JOptionPane.showMessageDialog(null, "Choose date!");
            return ;
        }
        
        if(fieldPetName.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter pet name!");
            return ;
        }
        
        if(fieldPetAge.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter age!");
            return ;
        }
        
//        if(fieldPetGender.getText().trim().isEmpty()){
//            JOptionPane.showMessageDialog(null, "Enter gender!");
//            return ;
//        }
        
        if(fieldPetType.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter pet type!");
            return ;
        }
        
        if(fieldPetBreed.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Enter breed!");
            return ;
        }
        
        if(fieldPlan.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(null, "Choose an insurance plan!");
            return ;
        }
        
        // create applicant and pet info
        Applicant a = business.getApplicantsDirectory().createApplicant(fieldFirstName.getText(),
                fieldLastName.getText(), fieldDate.getDate());
        
        
        
        Pet p = a.createPet(fieldPetName.getText(), Integer.parseInt(fieldPetAge.getText()),fieldPetGender.isSelected() ,
                fieldPetType.getText() , fieldPetBreed.getText());
        
        p.setInsurancePlan((Insurance) fieldPlan.getSelectedItem());
        
        
        // create vaccination 
        if(!fieldVaccinationName.getText().trim().isEmpty()){
            p.createVaccination(fieldVaccinationName.getText(), fieldCourseCompleted.isSelected());
        }
        
        
        JOptionPane.showMessageDialog(null, "Add successfully!");
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox fieldCourseCompleted;
    private com.toedter.calendar.JDateChooser fieldDate;
    private javax.swing.JTextField fieldFirstName;
    private javax.swing.JTextField fieldLastName;
    private javax.swing.JTextField fieldPetAge;
    private javax.swing.JTextField fieldPetBreed;
    private javax.swing.JCheckBox fieldPetGender;
    private javax.swing.JTextField fieldPetName;
    private javax.swing.JTextField fieldPetType;
    private javax.swing.JComboBox fieldPlan;
    private javax.swing.JTextField fieldVaccinationName;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
